# Generated by Django 3.1 on 2020-09-04 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='choice',
            table='choice',
        ),
        migrations.AlterModelTable(
            name='profilepicmodel',
            table='ProfilePicModel',
        ),
        migrations.AlterModelTable(
            name='question',
            table='question',
        ),
    ]
