# Generated by Django 3.1 on 2020-09-09 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20200904_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilepicmodel',
            name='role',
            field=models.CharField(default='User', max_length=10),
        ),
        migrations.AlterField(
            model_name='profilepicmodel',
            name='image',
            field=models.ImageField(blank=True, upload_to='static/images'),
        ),
    ]
