# Generated by Django 3.1 on 2020-09-09 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20200909_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilepicmodel',
            name='role',
            field=models.CharField(max_length=10),
        ),
    ]
